source 'https://rubygems.org'

# Sinatra
gem 'sinatra'

#to start service
gem 'foreman'

# DataMapper gems
gem 'dm-core'
gem 'dm-timestamps'
gem 'dm-migrations'
gem 'dm-serializer'
gem 'dm-sqlite-adapter'

# Bcrypt
gem 'bcrypt'
